[package]
name = "apt-cmd"
description = "Async library for interacting with apt commands"
version = "0.4.0"
license = "MPL-2.0"
keywords = ["apt", "async", "tokio", "debian"]
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0.53"
as-result = "0.2.1"
async-stream = "0.3.2"
derive_more = "0.99.17"
futures = "0.3.21"
hex = "0.4.3"
md-5 = "0.10.0"
procfs = "0.12.0"
sha-1 = "0.10.0"
thiserror = "1.0.30"
async-shutdown = "0.1.2"

[dependencies.async-fetcher]
git = "https://github.com/pop-os/async-fetcher"

[dependencies.tokio]
version = "1.16.1"
features = ["fs", "io-util", "process", "rt", "sync", "time"]

[dependencies.tokio-stream]
version = "0.1.8"
features = ["io-util"]

[dependencies.tokio-util]
version = "0.7.0"
features = ["compat"]

[dev-dependencies.tokio]
version = "1.16.1"
features = ["full"]

[features]
