[package]
name = "apt-cmd"
description = "Async library for interacting with apt commands"
version = "0.3.0"
license = "MPL-2.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0.51"
as-result = "0.2.1"
async-barrier = "1.1.0"
async-fs = "1.5.0"
async-io = "1.6.0"
async-process = "1.3.0"
async-stream = "0.3.2"
async-task = "4.0.3"
derive_more = "0.99.17"
flume = "0.10.9"
futures = "0.3.18"
futures-util = "0.3.18"
hex = "0.4.3"
isahc = "1.6.0"
md-5 = "0.10.0"
procfs = "0.12.0"
sha-1 = "0.10.0"
smolscale = "0.3.16"
thiserror = "1.0.30"

[dev-dependencies]
anyhow = "1.0.51"
