[package]
name = "apt-cmd"
description = "Async library for interacting with apt commands"
version = "0.2.0"
license = "LGPL-3.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
as-result = "0.2"
async-barrier = "1.1"
async-fs = "1.5"
async-io = "1.6"
async-process = "1.1"
async-stream = "0.3"
async-task = "4.0"
derive_more = "0.99"
flume = "0.10"
futures = "0.3"
futures-util = "0.3"
hex = "0.4"
isahc = "1.3"
md-5 = "0.9"
procfs = "0.11"
smolscale = "0.3"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1.0"
